# Copyright 2017, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: cpp

sudo: false

os:
  - linux

before_install:
  - export CC=
  - export CXX=

install:
  - git clone https://github.com/staticlibs/android-ndk-r9d-arm-linux-androideabi-4.8.git ../android-ndk

before_script:
  - git submodule update --init --recursive
  - cd ..
  - git clone https://github.com/staticlibs/cmake.git
  - git clone https://github.com/staticlibs/staticlib_config.git

script:
  - set -e
  - mkdir build-android
  - pushd build-android
  - cmake ../external_openssl/test -DCMAKE_BUILD_TYPE=Release -DSTATICLIB_TOOLCHAIN=android_armeabi_gcc -DANDROID_TOOLCHAIN_DIR=`pwd`/../android-ndk
  - make

notifications:
  email:
    on_success: always
