#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/home/alex/apps/android-ndk-r9d-x86-linux-android-4.8/i686-linux-android//bin/gcc -DOPENSSL_THREADS -D_REENTRANT -fPIC -DANDROID -mandroid --sysroot=/home/alex/apps/android-ndk-r9d-x86-linux-android-4.8/sysroot/ -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "android"
  #define DATE "Tue Nov  8 15:05:39 GMT 2016"
#endif
