#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/home/alex/apps/android-ndk-r9d-arm-linux-androideabi-4.8/arm-linux-androideabi/bin/gcc -DOPENSSL_THREADS -D_REENTRANT -fPIC -DANDROID -mandroid --sysroot=/home/alex/apps/android-ndk-r9d-arm-linux-androideabi-4.8/sysroot/ -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "android"
  #define DATE "Tue Nov  8 14:15:42 GMT 2016"
#endif
