@echo off

echo f | xcopy /f /y "../../crypto/aes/aes.h" aes.h
echo f | xcopy /f /y "../../crypto/asn1/asn1.h" asn1.h
echo f | xcopy /f /y "../../crypto/asn1/asn1_mac.h" asn1_mac.h
echo f | xcopy /f /y "../../crypto/asn1/asn1t.h" asn1t.h
echo f | xcopy /f /y "../../crypto/bio/bio.h" bio.h
echo f | xcopy /f /y "../../crypto/bf/blowfish.h" blowfish.h
echo f | xcopy /f /y "../../crypto/bn/bn.h" bn.h
echo f | xcopy /f /y "../../crypto/buffer/buffer.h" buffer.h
echo f | xcopy /f /y "../../crypto/camellia/camellia.h" camellia.h
echo f | xcopy /f /y "../../crypto/cast/cast.h" cast.h
echo f | xcopy /f /y "../../crypto/cmac/cmac.h" cmac.h
echo f | xcopy /f /y "../../crypto/cms/cms.h" cms.h
echo f | xcopy /f /y "../../crypto/comp/comp.h" comp.h
echo f | xcopy /f /y "../../crypto/conf/conf_api.h" conf_api.h
echo f | xcopy /f /y "../../crypto/conf/conf.h" conf.h
echo f | xcopy /f /y "../../crypto/crypto.h" crypto.h
echo f | xcopy /f /y "../../crypto/des/des.h" des.h
echo f | xcopy /f /y "../../crypto/des/des_old.h" des_old.h
echo f | xcopy /f /y "../../crypto/dh/dh.h" dh.h
echo f | xcopy /f /y "../../crypto/dsa/dsa.h" dsa.h
echo f | xcopy /f /y "../../crypto/dso/dso.h" dso.h
echo f | xcopy /f /y "../../ssl/dtls1.h" dtls1.h
echo f | xcopy /f /y "../../crypto/ebcdic.h" ebcdic.h
echo f | xcopy /f /y "../../crypto/ecdh/ecdh.h" ecdh.h
echo f | xcopy /f /y "../../crypto/ecdsa/ecdsa.h" ecdsa.h
echo f | xcopy /f /y "../../crypto/ec/ec.h" ec.h
echo f | xcopy /f /y "../../crypto/engine/engine.h" engine.h
echo f | xcopy /f /y "../../e_os2.h" e_os2.h
echo f | xcopy /f /y "../../crypto/err/err.h" err.h
echo f | xcopy /f /y "../../crypto/evp/evp.h" evp.h
echo f | xcopy /f /y "../../crypto/hmac/hmac.h" hmac.h
echo f | xcopy /f /y "../../crypto/idea/idea.h" idea.h
echo f | xcopy /f /y "../../crypto/krb5/krb5_asn.h" krb5_asn.h
echo f | xcopy /f /y "../../ssl/kssl.h" kssl.h
echo f | xcopy /f /y "../../crypto/lhash/lhash.h" lhash.h
echo f | xcopy /f /y "../../crypto/md4/md4.h" md4.h
echo f | xcopy /f /y "../../crypto/md5/md5.h" md5.h
echo f | xcopy /f /y "../../crypto/mdc2/mdc2.h" mdc2.h
echo f | xcopy /f /y "../../crypto/modes/modes.h" modes.h
echo f | xcopy /f /y "../../crypto/objects/objects.h" objects.h
echo f | xcopy /f /y "../../crypto/objects/obj_mac.h" obj_mac.h
echo f | xcopy /f /y "../../crypto/ocsp/ocsp.h" ocsp.h
echo f | xcopy /f /y "../../crypto/opensslconf.h" opensslconf.h
echo f | xcopy /f /y "../../crypto/opensslv.h" opensslv.h
echo f | xcopy /f /y "../../crypto/ossl_typ.h" ossl_typ.h
echo f | xcopy /f /y "../../crypto/pem/pem2.h" pem2.h
echo f | xcopy /f /y "../../crypto/pem/pem.h" pem.h
echo f | xcopy /f /y "../../crypto/pkcs12/pkcs12.h" pkcs12.h
echo f | xcopy /f /y "../../crypto/pkcs7/pkcs7.h" pkcs7.h
echo f | xcopy /f /y "../../crypto/pqueue/pqueue.h" pqueue.h
echo f | xcopy /f /y "../../crypto/rand/rand.h" rand.h
echo f | xcopy /f /y "../../crypto/rc2/rc2.h" rc2.h
echo f | xcopy /f /y "../../crypto/rc4/rc4.h" rc4.h
echo f | xcopy /f /y "../../crypto/ripemd/ripemd.h" ripemd.h
echo f | xcopy /f /y "../../crypto/rsa/rsa.h" rsa.h
echo f | xcopy /f /y "../../crypto/stack/safestack.h" safestack.h
echo f | xcopy /f /y "../../crypto/seed/seed.h" seed.h
echo f | xcopy /f /y "../../crypto/sha/sha.h" sha.h
echo f | xcopy /f /y "../../crypto/srp/srp.h" srp.h
echo f | xcopy /f /y "../../ssl/srtp.h" srtp.h
echo f | xcopy /f /y "../../ssl/ssl23.h" ssl23.h
echo f | xcopy /f /y "../../ssl/ssl2.h" ssl2.h
echo f | xcopy /f /y "../../ssl/ssl3.h" ssl3.h
echo f | xcopy /f /y "../../ssl/ssl.h" ssl.h
echo f | xcopy /f /y "../../crypto/stack/stack.h" stack.h
echo f | xcopy /f /y "../../crypto/symhacks.h" symhacks.h
echo f | xcopy /f /y "../../ssl/tls1.h" tls1.h
echo f | xcopy /f /y "../../crypto/ts/ts.h" ts.h
echo f | xcopy /f /y "../../crypto/txt_db/txt_db.h" txt_db.h
echo f | xcopy /f /y "../../crypto/ui/ui_compat.h" ui_compat.h
echo f | xcopy /f /y "../../crypto/ui/ui.h" ui.h
echo f | xcopy /f /y "../../crypto/whrlpool/whrlpool.h" whrlpool.h
echo f | xcopy /f /y "../../crypto/x509/x509.h" x509.h
echo f | xcopy /f /y "../../crypto/x509v3/x509v3.h" x509v3.h
echo f | xcopy /f /y "../../crypto/x509/x509_vfy.h" x509_vfy.h
