#!/bin/sh

ln -s ../../crypto/aes/aes.h
ln -s ../../crypto/asn1/asn1.h
ln -s ../../crypto/asn1/asn1_mac.h
ln -s ../../crypto/asn1/asn1t.h
ln -s ../../crypto/bf/blowfish.h
ln -s ../../crypto/bio/bio.h
ln -s ../../crypto/bn/bn.h
ln -s ../../crypto/buffer/buffer.h
ln -s ../../crypto/camellia/camellia.h
ln -s ../../crypto/cast/cast.h
ln -s ../../crypto/cmac/cmac.h
ln -s ../../crypto/cms/cms.h
ln -s ../../crypto/comp/comp.h
ln -s ../../crypto/conf/conf_api.h
ln -s ../../crypto/conf/conf.h
ln -s ../../crypto/crypto.h
ln -s ../../crypto/des/des.h
ln -s ../../crypto/des/des_old.h
ln -s ../../crypto/dh/dh.h
ln -s ../../crypto/dsa/dsa.h
ln -s ../../crypto/dso/dso.h
ln -s ../../crypto/ebcdic.h
ln -s ../../crypto/ecdh/ecdh.h
ln -s ../../crypto/ecdsa/ecdsa.h
ln -s ../../crypto/ec/ec.h
ln -s ../../crypto/engine/engine.h
ln -s ../../crypto/err/err.h
ln -s ../../crypto/evp/evp.h
ln -s ../../crypto/hmac/hmac.h
ln -s ../../crypto/idea/idea.h
ln -s ../../crypto/krb5/krb5_asn.h
ln -s ../../crypto/lhash/lhash.h
ln -s ../../crypto/md4/md4.h
ln -s ../../crypto/md5/md5.h
ln -s ../../crypto/mdc2/mdc2.h
ln -s ../../crypto/modes/modes.h
ln -s ../../crypto/objects/objects.h
ln -s ../../crypto/objects/obj_mac.h
ln -s ../../crypto/ocsp/ocsp.h
ln -s ../../crypto/opensslconf.h
ln -s ../../crypto/opensslv.h
ln -s ../../crypto/ossl_typ.h
ln -s ../../crypto/pem/pem2.h
ln -s ../../crypto/pem/pem.h
ln -s ../../crypto/pkcs12/pkcs12.h
ln -s ../../crypto/pkcs7/pkcs7.h
ln -s ../../crypto/pqueue/pqueue.h
ln -s ../../crypto/rand/rand.h
ln -s ../../crypto/rc2/rc2.h
ln -s ../../crypto/rc4/rc4.h
ln -s ../../crypto/ripemd/ripemd.h
ln -s ../../crypto/rsa/rsa.h
ln -s ../../crypto/seed/seed.h
ln -s ../../crypto/sha/sha.h
ln -s ../../crypto/srp/srp.h
ln -s ../../crypto/stack/safestack.h
ln -s ../../crypto/stack/stack.h
ln -s ../../crypto/symhacks.h
ln -s ../../crypto/ts/ts.h
ln -s ../../crypto/txt_db/txt_db.h
ln -s ../../crypto/ui/ui_compat.h
ln -s ../../crypto/ui/ui.h
ln -s ../../crypto/whrlpool/whrlpool.h
ln -s ../../crypto/x509v3/x509v3.h
ln -s ../../crypto/x509/x509.h
ln -s ../../crypto/x509/x509_vfy.h
ln -s ../../e_os2.h
ln -s ../../ssl/dtls1.h
ln -s ../../ssl/kssl.h
ln -s ../../ssl/srtp.h
ln -s ../../ssl/ssl23.h
ln -s ../../ssl/ssl2.h
ln -s ../../ssl/ssl3.h
ln -s ../../ssl/ssl.h
ln -s ../../ssl/tls1.h
